plugins {
    id 'application'
    alias(libs.plugins.javafx)
}

javafx {
    version = '22.0.1'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'io.github.k7t3.simplefx.Main'
    applicationName = 'Simple JavaFX App'
}

dependencies {
    implementation libs.atlantafx.base
}
