spring:
  ai:
    mcp:
      server:
        name: fxgraph-mcp-server
        version: 1.0.0
        type: SYNC
        stdio: true
  main:
    banner-mode: off
    web-application-type: none
    log-startup-info: false

logging:
  level:
    root: OFF
